-- 업체스펙
ALTER TABLE COMP_SPEC_TB
	DROP FOREIGN KEY FK_COMP_TB_TO_COMP_SPEC_TB; -- 업체 -> 업체스펙

-- 업체스펙
ALTER TABLE COMP_SPEC_TB
	DROP FOREIGN KEY FK_SPEC_TB_TO_COMP_SPEC_TB; -- 스펙 상세 -> 업체스펙

-- 업체사진
ALTER TABLE COMP_IMG_TB
	DROP FOREIGN KEY FK_COMP_TB_TO_COMP_IMG_TB; -- 업체 -> 업체사진

-- 모임
ALTER TABLE MEET_TB
	DROP FOREIGN KEY FK_MEMB_TB_TO_MEET_TB; -- 회원 -> 모임

-- 모임
ALTER TABLE MEET_TB
	DROP FOREIGN KEY FK_COMP_TB_TO_MEET_TB; -- 업체 -> 모임

-- 업체클래스
ALTER TABLE COMP_CATE_TB
	DROP FOREIGN KEY FK_COMP_TB_TO_COMP_CATE_TB; -- 업체 -> 업체클래스

-- 업체클래스
ALTER TABLE COMP_CATE_TB
	DROP FOREIGN KEY FK_CATE_TB_TO_COMP_CATE_TB; -- 클래스 -> 업체클래스

-- 추천클래스
ALTER TABLE RCMD_CATE_TB
	DROP FOREIGN KEY FK_MEET_TB_TO_RCMD_CATE_TB; -- 모임 -> 추천클래스

-- 추천클래스
ALTER TABLE RCMD_CATE_TB
	DROP FOREIGN KEY FK_CATE_TB_TO_RCMD_CATE_TB; -- 클래스 -> 추천클래스

-- 참여자
ALTER TABLE PARTI_TB
	DROP FOREIGN KEY FK_MEET_TB_TO_PARTI_TB; -- 모임 -> 참여자

-- 참여자
ALTER TABLE PARTI_TB
	DROP FOREIGN KEY FK_MEMB_TB_TO_PARTI_TB; -- 회원 -> 참여자

-- 좋아요업체
ALTER TABLE LIKE_COMP_TB
	DROP FOREIGN KEY FK_MEET_TB_TO_LIKE_COMP_TB; -- 모임 -> 좋아요업체

-- 좋아요업체
ALTER TABLE LIKE_COMP_TB
	DROP FOREIGN KEY FK_PARTI_TB_TO_LIKE_COMP_TB; -- 참여자 -> 좋아요업체

-- 좋아요업체
ALTER TABLE LIKE_COMP_TB
	DROP FOREIGN KEY FK_COMP_TB_TO_LIKE_COMP_TB; -- 업체 -> 좋아요업체

-- 추천장소
ALTER TABLE RCMD_PLC_TB
	DROP FOREIGN KEY FK_MEET_TB_TO_RCMD_PLC_TB; -- 모임 -> 추천장소

-- 스펙 상세
ALTER TABLE SPEC_TB
	DROP FOREIGN KEY FK_CATE_TB_TO_SPEC_TB; -- 클래스 -> 스펙 상세

-- 업체
ALTER TABLE COMP_TB
	DROP PRIMARY KEY; -- 업체 기본키

-- 업체스펙
ALTER TABLE COMP_SPEC_TB
	DROP PRIMARY KEY; -- 업체스펙 기본키

-- 회원
ALTER TABLE MEMB_TB
	DROP PRIMARY KEY; -- 회원 기본키

-- 업체사진
ALTER TABLE COMP_IMG_TB
	DROP PRIMARY KEY; -- 업체사진 기본키

-- 모임
ALTER TABLE MEET_TB
	DROP PRIMARY KEY; -- 모임 기본키

-- 클래스
ALTER TABLE CATE_TB
	DROP PRIMARY KEY; -- 클래스 기본키

-- 카테고리
ALTER TABLE CATE_TB
	DROP PRIMARY KEY; -- 카테고리 기본키

-- 업체클래스
ALTER TABLE COMP_CATE_TB
	DROP PRIMARY KEY; -- 업체클래스 기본키

-- 추천클래스
ALTER TABLE RCMD_CATE_TB
	DROP PRIMARY KEY; -- 추천클래스 기본키

-- 참여자
ALTER TABLE PARTI_TB
	DROP PRIMARY KEY; -- 참여자 기본키

-- 좋아요업체
ALTER TABLE LIKE_COMP_TB
	DROP PRIMARY KEY; -- 좋아요업체 기본키

-- 스펙 상세
ALTER TABLE SPEC_TB
	DROP PRIMARY KEY; -- 스펙 상세 기본키

-- 회원 인덱스
DROP INDEX IX_MEMB_TB ON MEMB_TB;

-- 업체 유니크 인덱스
DROP INDEX UIX_COMP_TB ON COMP_TB;

-- 회원 유니크 인덱스
DROP INDEX UIX_MEMB_TB ON MEMB_TB;

-- 클래스 유니크 인덱스
DROP INDEX UIX_CATE_TB ON CATE_TB;

-- 업체
DROP TABLE IF EXISTS COMP_TB RESTRICT;

-- 업체스펙
DROP TABLE IF EXISTS COMP_SPEC_TB RESTRICT;

-- 회원
DROP TABLE IF EXISTS MEMB_TB RESTRICT;

-- 업체사진
DROP TABLE IF EXISTS COMP_IMG_TB RESTRICT;

-- 모임
DROP TABLE IF EXISTS MEET_TB RESTRICT;

-- 클래스
DROP TABLE IF EXISTS CATE_TB RESTRICT;

-- 카테고리
DROP TABLE IF EXISTS CATE_TB RESTRICT;

-- 업체클래스
DROP TABLE IF EXISTS COMP_CATE_TB RESTRICT;

-- 추천클래스
DROP TABLE IF EXISTS RCMD_CATE_TB RESTRICT;

-- 참여자
DROP TABLE IF EXISTS PARTI_TB RESTRICT;

-- 좋아요업체
DROP TABLE IF EXISTS LIKE_COMP_TB RESTRICT;

-- 추천장소
DROP TABLE IF EXISTS RCMD_PLC_TB RESTRICT;

-- 스펙 상세
DROP TABLE IF EXISTS SPEC_TB RESTRICT;
